Repository UnBArqDsw2021-1/2021.1_G04_Cardeal, pull requests merged in 2021-09, with the labels that each got.

#114 Bugfix/prototipo alta
  docs/modelagem/identidadeVisual.md
  docs/modelagem/prototipo_alta.md
  docs/padroesDeProjeto/correcoes_E2.md
  mkdocs.yml
Labels: documentation, BUGFIX

#132 Bugfix/id visual
  docs/desenhoSoftwareBase/img/IdentidadeVisual/symbol.png
  docs/modelagem/debateIdentidadeVisual.md
  docs/modelagem/identidadeVisual.md
  docs/modelagem/prototipo_alta.md
  docs/padroesDeProjeto/correcoes_E2.md
Labels: DOCUMENTAÇÃO, BUGFIX

#129 Add template method page
  docs/modelagem/identidadeVisual.md
  docs/modelagem/prototipo_alta.md
  docs/padroesDeProjeto/correcoes_E2.md
  docs/padroesDeProjeto/gofs_comportamentais_template.md
  docs/padroesDeProjeto/img/exemplo_TemplateMethod1.png
  docs/padroesDeProjeto/img/projeto_template.png
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#134 Ata 10/09/2021
  docs/padroesDeProjeto/atas/10-09-21.md
  docs/padroesDeProjeto/planning_poker.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#135 Adição do GRASP - Controlador
  docs/padroesDeProjeto/GRASPs.md
  docs/padroesDeProjeto/img/clientController.png
  docs/padroesDeProjeto/img/controller1.svg
  docs/padroesDeProjeto/img/controller2.svg
  docs/padroesDeProjeto/img/propertyController.png
Labels: DOCUMENTAÇÃO

#137 Atas de Reuniões
  docs/padroesDeProjeto/atas/06-09-21.md
  docs/padroesDeProjeto/atas/10-09-21.md
  docs/padroesDeProjeto/atas/13-09-21.md
  docs/padroesDeProjeto/atas/17-09-21.md
  docs/padroesDeProjeto/atas/30-08-21.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#139 Bugfix/Diagrama de Sequencia
  docs/modelagem/diagrama_sequencia.md
Labels: BUGFIX

#150 GRASPs - Fabricação Pura e Variações Protegidas
  docs/padroesDeProjeto/GRASPs.md
Labels: DOCUMENTAÇÃO

#151 GRASP - Baixo Acoplamento
  docs/padroesDeProjeto/GRASPs.md
  docs/padroesDeProjeto/img/clientsService.jpeg
Labels: DOCUMENTAÇÃO

#152 GRASP - Indireção
  docs/padroesDeProjeto/GRASPs.md
Labels: DOCUMENTAÇÃO

#153 GRASPS
  docs/padroesDeProjeto/GRASPs.md
  docs/padroesDeProjeto/gofs_criacionais.md
  docs/padroesDeProjeto/img/grasp-criador-property.svg
  docs/padroesDeProjeto/img/grasp-criador.svg
Labels: DOCUMENTAÇÃO

#149 Documento de Correções - Diagrama de Sequência
  docs/padroesDeProjeto/correcoes_E2.md
Labels: DOCUMENTAÇÃO

#162 Kanban
  docs/modelagem/diagrama_estados.md
  docs/padroesDeProjeto/correcoes_E2.md
  docs/padroesDeProjeto/img/kanban.png
  docs/padroesDeProjeto/img/planning_poker.png
  docs/padroesDeProjeto/kambam.md
  docs/padroesDeProjeto/kanban.md
  docs/padroesDeProjeto/planning_poker.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO
