Repository UnBArqDsw2021-1/2021.1_G04_Cardeal, pull requests merged in 2021-08, with the labels that each got.

#68 Feature/identidade visual
  docs/desenhoSoftwareBase/img/IdentidadeVisual/black.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/corPrincipal.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/corSecundaria.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/fonte1.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/fonteSite.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/grey.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/idVisual.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/logo.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/lora.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/nomes.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/purple.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/red.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/resultado.pdf
  docs/desenhoSoftwareBase/img/IdentidadeVisual/resultadoCor.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/sora.png
  docs/desenhoSoftwareBase/img/IdentidadeVisual/white.png
  docs/modelagem/debateIdentidadeVisual.md
  docs/modelagem/identidadeVisual.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#61 Corrigindo documento de léxicos
  docs/desenhoSoftwareBase/lexico.md
Labels: DOCUMENTAÇÃO, BUGFIX

#62 Feature/diagrama casos de uso
  docs/modelagem/diagrama_casos_de_uso.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#63 Feature/diagrama_relacional
  docs/diagramaRelacional/brModelo/Cardeal_Conceitual.brM3
  docs/diagramaRelacional/brModelo/Cardeal_Lógico.brM3
  docs/diagramaRelacional/brModelo/Cardeal_Lógico.sql
  docs/diagramaRelacional/diagrama_relacional.md
  docs/diagramaRelacional/img/Cardeal_Conceitual.jpg
  docs/diagramaRelacional/img/Cardeal_Logico.jpg
  docs/index.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#74 Feature/diagrama abstrata
  docs/modelagem/diagrama_abstrata.md
  docs/modelagem/img/classeAbstrata.png
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#58 Adicionando diagrama de sequência
  docs/modelagem/diagrama_sequencia.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#71 created package diagram page
  docs/desenhoSoftwareBase/img/diagrama_pacotes.png
  docs/modelagem/debateIdentidadeVisual.md
  docs/modelagem/diagrama_pacotes.md
  docs/modelagem/identidadeVisual.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#78 Feature/diagrama comunicacao
  docs/desenhoSoftwareBase/BPMN/BPMN-1.svg
  docs/desenhoSoftwareBase/BPMN/BPMN-2.svg
  docs/desenhoSoftwareBase/BPMN/BPMN-3.svg
  docs/desenhoSoftwareBase/modelagemBpmn.md
  docs/modelagem/correcoes_E1.md
  docs/modelagem/diagrama_comunicacao.md
  mkdocs.yml
Labels: DOCUMENTAÇÃO

#77 Correção no documento Rich Picture
  docs/desenhoSoftwareBase/richPicture.md
  docs/modelagem/correcoes_E1.md
Labels: BUGFIX

#75 Protótipo de Alta fidelidade
  docs/modelagem/debateIdentidadeVisual.md
  docs/modelagem/prototipo_alta.md
  docs/modelagem/prototipo_alta/1-home.png
  docs/modelagem/prototipo_alta/10-guia-estilo.png
  docs/modelagem/prototipo_alta/2-busca-imoveis.png
  docs/modelagem/prototipo_alta/3-lista-imoveis.png
  docs/modelagem/prototipo_alta/4-detalhe-imovel.png
  docs/modelagem/prototipo_alta/5-cadastro.png
  docs/modelagem/prototipo_alta/6-cadastro-imovel.png
  docs/modelagem/prototipo_alta/7-lista-imoveis-corretor.png
  docs/modelagem/prototipo_alta/8-minhas-visitas.png
  docs/modelagem/prototipo_alta/9-form-generico.png
  mkdocs.yml
Labels: PROTOTIPAÇÃO
